import type { Module } from "../types"

export const awsModule7: Module = {
  id: 7,
  title: "Security: Shared Responsibility & IAM",
  status: "upcoming",
  lessons: [
    {
      name: "The AWS Shared Responsibility Model",
      minutes: 12,
      intro: "The most-tested concept in CLF-C02: who secures what.",
      content: `### The shared responsibility model

**AWS is responsible for security OF the cloud (the infrastructure). You are responsible for security IN the cloud (what you run on it).**

\`\`\`text
AWS:  physical data centers, hardware, networking, virtualization (hypervisor)
You:  guest OS, applications, code, customer data, IAM, encryption configs
\`\`\`

| Responsibility | Who owns it |
|----------------|-------------|
| Physical security of data centers | AWS |
| Hosts, storage, networking hardware | AWS |
| Virtualization layer | AWS |
| Patch the guest OS you run | **You** |
| Configure security groups / firewalls | **You** |
| Encrypt and protect your data | **You** |
| Identity & Access Management | **You** |
| Compliance of the services you use | Both (per service) |

### It depends on the service

With **RDS**, AWS manages the database engine • with **EC2**, **you** manage the OS and everything on it. In general, **managed and serverless services shift more responsibility to AWS**.

### Exam-style questions

- "Who is responsible for patching the operating system of an EC2 instance?" → **the customer**
- "Who maintains the physical security of AWS data centers?" → **AWS**
- "Who is responsible for patching the RDS database engine?" → **AWS**
- "AWS is responsible for security **of** the cloud; you are responsible for security **in** the cloud."

> **Exam tip:** Remember the physical→logical split. Anything physical/hardware = AWS. Anything on top of the OS that you run = you.`,
    },
    {
      name: "IAM: Users, Groups, Roles & Policies",
      minutes: 14,
      intro: "Identity and Access Management — the heart of AWS security.",
      content: `### What is IAM?

**AWS Identity and Access Management (IAM)** lets you control **who** (identity) can do **what** (permissions) to which AWS resources. It is a **global service** — IAM applies across all regions.

### IAM components

| Component | What it is |
|-----------|-----------|
| **User** | A person or application that needs AWS access (has credentials) |
| **Group** | A collection of users (e.g. "Developers"); permissions applied to the group |
| **Role** | An identity you **assume** to get temporary permissions (no long-term credentials) |
| **Policy** | A JSON document granting (allow/deny) permissions |
| **IAM Policy** | Written in JSON — defines actions ("s3:*", "ec2:DescribeInstances") and resources |

### Key behavior

- **Root account** — created when you sign up; has full access. **Never use it for daily work.**
- **Least privilege** — grant only the permissions needed
- **Temporary credentials** via roles are more secure than embedding keys
- **IAM users have no AWS permissions by default** — you must attach policies/groups

### IAM Roles (exam favorite)

- Roles provide **temporary credentials** (via STS)
- **Best for:** an EC2 instance accessing S3 without storing access keys in the instance; application access; cross-account access
- Example: give an **EC2 instance a role** so its apps can read from S3 — no keys stored on the server

### When to use what

| Scenario | Use |
|----------|-----|
| Your employee (permanent) | IAM User |
| Group of users with shared permissions | IAM Group |
| Application/EC2 needing temporary access | IAM **Role** |

> **Exam tip:** Roles = temporary, no long-lived credentials, the secure choice for apps/machines. "Least privilege" is almost always the best-practice answer.`,
    },
    {
      name: "MFA & Access Keys",
      minutes: 8,
      intro: "Multi-factor authentication, access keys, and how to protect credentials.",
      content: `### Multi-Factor Authentication (MFA)

- Adds a **second layer of security** beyond username + password
- Requires an extra code generated by: virtual MFA app (e.g. Google Authenticator on phone), hardware MFA key, U2F security key
- **Best practice:** enable MFA on the **root account** and **all privileged users**

> **Exam tip:** "Improve security of your account / protect root account" → **enable MFA**. Brute-force protection is a big exam answer.

### Access keys

- **Access key ID** + **secret access key** = programmatic credentials for the CLI/SDK
- **NEVER share them.** They're used to make API calls on your behalf
- Treat them like passwords — rotate them, delete unused keys
- Prefer **IAM roles for EC2** over storing keys on instances

### IAM security best practices (memorize)

1. Lock away root user access keys
2. Enable MFA for root and all users
3. Grant **least privilege** — minimal permissions
4. Use **roles** for applications/services
5. Use groups to assign permissions to users
6. Audit via **IAM Access Analyzer** and **CloudTrail**
7. Use **IAM password policies** and rotate keys regularly

### Root account safeguards

- Can't fully delete root user
- Use a **strong password + MFA**
- Sign in as root only for account-level tasks

> **Exam tip:** Every "security best practice" answer involves MFA, least privilege, roles, and avoiding long-lived keys.`,
    },
    {
      name: "Compliance & AWS Compliance Resources",
      minutes: 10,
      intro: "Encryption basics, compliance programs, and artifacts.",
      content: `### Encryption basics (in the cloud)

Encryption protects data **at rest** (stored) and **in transit** (moving):

- **At rest** — encrypt stored data (EBS, S3 via **SSE**, databases, keys via **KMS**)
- **In transit** — encrypt traffic (TLS/SSL, HTTPS)
- **AWS Key Management Service (KMS)** manages the encryption keys
- **AWS CloudHSM** — hardware security modules for customers who need to manage keys in dedicated hardware

### Compliance programs & frameworks

AWS adheres to compliance standards so customers can run regulated workloads:

| Program | What it covers |
|---------|----------------|
| **HIPAA** | Healthcare data (PHI) |
| **PCI DSS** | Credit card / payment data |
| **SOC 1/2/3** | Controls & auditing |
| **GDPR** | European personal data |
| **FedRAMP / ISO 27001** | Government / security management |

### AWS compliance resources

| Resource | What it does |
|----------|--------------|
| **AWS Artifact** | **Self-service portal** to download AWS compliance reports and agreements (SOC, PCI, ISO) on demand |
| **AWS Artifact Agreements** | Sign and manage agreements online |
| **AWS Compliance Center** | Central hub for compliance & security info |
| **Amazon GuardDuty** | Continuous **threat detection** (analyzes findings) |

> **Exam tip:** "Where do I download AWS compliance reports?" → **AWS Artifact**. "Healthcare data" → HIPAA. "Credit card payments" → PCI DSS.

### Your responsibility in compliance

- Choose compliant services and regions
- Configure them correctly (encryption, access)
- Use third-party and AWS audits as evidence

> **Exam tip:** "Compliance documentation / reports access" = AWS Artifact. "GDPR data residency" = choose a specific Region.`,
    },
  ],
}